[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages =  ["src"]

[project]
name = "GambaStatsBot"
version = "0.1.0"
authors = [
    {name = "Niko Typpö"},
]
description = "Telegram bot that tracks slot machine statistics."
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "asyncpg-stubs>=0.31.3",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.2",
    "python-telegram-bot>=22.8",
]

[dependency-groups]
dev = [
  {include-group = "lint"},
  {include-group = "test"},
  {include-group = "typing"},
]
lint = [
    "ruff>=0.15.20",
]
test = [
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
]
typing = [
    "ty>=0.0.65",
]
